### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by Hanyu-Xue** [chi0tzp/FALCO#1]
Hi, 

Thank you for your excellent work! I'm eagerly looking forward to citing your contributions. Could you please provide information on the code release?

**Comment by chi0tzp** [comment]
Hi @Hanyu-Xue, thanks for your interest in our work. We plan to release the code in a few days' time. I'll close the issue as soon as I push the code, so you'll be notified.

**Comment by chi0tzp** [comment]
Dear @Hanyu-Xue, FYI, the code has just been added.
