### ISSUE TITLE
CelebA HQ

### ISSUE THREAD

**Issue by Sarah47393** [chi0tzp/FALCO#10]
Hello, thanks for your work
I didn't find any link or a description to download CelebA HQ, could you please provide me wth the link, or is there any other solution to use CelebA instead of CelebA HQ
Thank you

**Comment by chi0tzp** [comment]
Hi @Sarah47393, you can download the CelebA-HQ dataset following the instructions [here](https://github.com/switchablenorms/CelebAMask-HQ). For instance, you can use this Google Drive [link](https://drive.google.com/open?id=1badu11NqxGf6qM3PTTooQDJvQbejgbTv).

You can relatively easily create another class for CelebA, if I have time I'll add a class for a generic dataset.
