### ISSUE TITLE
Face Alignment Errors

### ISSUE THREAD

**Issue by JamieCR1999** [chi0tzp/FALCO#11]
Thanks for the amazing work!
When I was performing an inversion operation using the CelebA dataset, there were a lot of alignment errors. Is this a normal phenomenon? Or is there a problem with my processing method?

**Comment by chi0tzp** [comment]
Hi @SerJamie, thanks for your interest in our work!
Unfortunately, alignment errors can happen, and is part of the inversion process (e4e). I'm reporting in which images such errors happen, but otherwise e4e tries to do its best (i.e., not a fatal error in the anonymization process).

**Comment by JamieCR1999** [comment]
Ok, I understand, thank you for your response!
