### ISSUE TITLE
anonymize.py error

### ISSUE THREAD

**Issue by peihuan494** [chi0tzp/FALCO#12]
Hello, when I tried to execute anonymize.py, I found that there was no DataParallelPassthrough, anon_exp_dir, tensor2image function, could you share it? Thank you very much.
![1](https://github.com/user-attachments/assets/adaf2760-3cdd-446d-9f7b-cf4cad684bc0)

**Comment by chi0tzp** [comment]
Hi @peihuan494, these functions can be found in [lib/aux.py](https://github.com/chi0tzp/FALCO/blob/cvpr23/lib/aux.py) and you should be able to find them there already.

**Comment by peihuan494** [comment]
Thank you very much for your reply
