### ISSUE TITLE
What value of m (ID_MARGIN) was used across the paper? & What output scaling to use?

### ISSUE THREAD

**Issue by majedelhelou** [chi0tzp/FALCO#3]
Hello

1. Comparing the results in Table 1 to those in Table 4, it seems that m=0 was used for Table 1. I am trying to reproduce your results, is the value of m always 0 for all experiments in the paper (ignoring Figure 3)?
What is the difference between: "Ours (ID+attributes)" and "Ours" in Table 1?

2. In your inversion and anonymization scripts, when saving images you use the function `tensor2image` that has the adaptive option set to true by default. This uses adaptive scaling when scaling tensors to images and causes somewhat washed out images. Did you use adaptive scaling for the results you show in the paper / should I keep the adaptive scaling on when using your model or not?

Thank you.

**Comment by chi0tzp** [comment]
Dear @majedelhelou, thanks for your comment and apologies for taking me so long to respond -- it must have slipped through the cracks...

So,

1. Indeed m=0.0 is the value used for all main experiments. Regarding "ID+attributes" that should really have been "Attributes" only (i.e., only the attribute classification loss has been used).
2. Yes, adaptive option has been used in all cases, but to be fair I have experimented without it.

In the meantime, I have made available the whole anonymization process for CelebA-HQ (i.e., fake pool of images, features, nearest neighbors etc) for 11 values of m (m=0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0) [here](https://www.dropbox.com/scl/fi/flz8tchptxw8ql9471503/datasets.tar?rlkey=mvhjd1fy8w70k32pss8mm6sv2&st=j9b4t4aa&dl=1) (82.6 GiB).
