### ISSUE TITLE
Broken link to download pretrained models

### ISSUE THREAD

**Issue by JhEdLp** [chi0tzp/FALCO#4]

**Comment by bittnerma** [comment]
Second this!

`download_model.py` fails with:

```
Exception has occurred: ConnectionError
Error: https://www.dropbox.com/s/bemmhblro50fdk2/genforce.tar?dl=1
  File ".../FALCO/download_models.py", line 29, in download
    urllib.request.urlretrieve(src, tmp_tar, reporthook)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
I found this: https://github.com/genforce/genforce/blob/master/MODEL_ZOO.md which looks like it contains the stylegan2_ffhq1024.pth, but couldn't find the stylegan2_ffhq512.pth.

**Comment by chi0tzp** [comment]
Hi @bittnerma, @JhEdLp apologies, two links were broken. Fixed! Should work now.

**Comment by bittnerma** [comment]
Great, thank you!
