### ISSUE TITLE
Split test set IDs

### ISSUE THREAD

**Issue by JhEdLp** [chi0tzp/FALCO#5]
Hi, you can please share the TXT or JSON file, where contain the IDs of the Celeba-HQ test-set dataset used to obtain the quantitative results showed in the principal documents.

**Comment by chi0tzp** [comment]
Hi @JhEdLp, I've used this split:
[CelebAMask-HQ-attribute-anno.txt](https://github.com/chi0tzp/FALCO/files/13354270/CelebAMask-HQ-attribute-anno.txt)
[CelebA-HQ-to-CelebA-mapping.txt](https://github.com/chi0tzp/FALCO/files/13354271/CelebA-HQ-to-CelebA-mapping.txt)
[list_eval_partition.txt](https://github.com/chi0tzp/FALCO/files/13354272/list_eval_partition.txt)
