### ISSUE TITLE
Test on other datasets

### ISSUE THREAD

**Issue by belamarib** [chi0tzp/FALCO#8]
Hello there! Congrats for your work!

I would like to know if it's possible to test the anonymization on other datasets and not only the 3 that were provided.

**Comment by chi0tzp** [comment]
Hi @belamarib, thanks for your interest in our work. It is possible to apply our method to any dataset (labelled or unlabelled) granted that you build a new dataloader class for the said dataset. I'm planning to update the repo with such a class soon (branch: https://github.com/chi0tzp/FALCO/tree/cvpr23), but I can't make any promises right now. In the meantime, you can simple try to modify the CelebA-HQ class (https://github.com/chi0tzp/FALCO/blob/cvpr23/lib/celebahq.py) to work with your own data.

I will close this issue as soon as I push the aforementioned generic dataset class.

**Comment by belamarib** [comment]
Thanks for the answer, I will look into It!!
