### ISSUE TITLE
Error with download_models.py

### ISSUE THREAD

**Issue by amira-essawy** [chi0tzp/FALCO#9]
Hello, thanks for your work.
I have issued this error while running `python download_models.py` , can you help with that?
![image (3)](https://github.com/chi0tzp/FALCO/assets/118816526/ad3e71d4-ca66-4e09-9196-433b112b1a0b)

**Comment by chi0tzp** [comment]
Hi @amira-essawy, I can't reproduce your error. Would you mind removing your venv directory (`falco-venv` if you followed the installation guidelines in README.md) and install again the venv following the instructions? It should work.
